### ISSUE TITLE
reading tag problem

### ISSUE THREAD

**Issue by rr10** [sopan-sarkar/RDM6300_ESP8266#2]
hello I have a nodemcu v3 and the reader rdm6300.I can not read the tags how can I do? in the terminal I can read serial ready

![img_20180916_150833](https://user-images.githubusercontent.com/26082390/45596304-d6013f00-b9c2-11e8-839e-a5ecca75b3ff.jpg)
![img_20180916_150828](https://user-images.githubusercontent.com/26082390/45596305-d699d580-b9c2-11e8-8d9a-7c02a8f68e61.jpg)
![img_20180916_150815](https://user-images.githubusercontent.com/26082390/45596306-d699d580-b9c2-11e8-88d9-267d477604f7.jpg)

**Comment by sopan-sarkar** [comment]
@rr10 You have connected the Tx Rx cables in the wrong pins of ESP8266. Please follow my example where I have used the software serial library instead of the hardware serial. In the code I have defined the Tx and Rx pins as follows: 
#define RFID_RX_PIN 2
#define RFID_TX_PIN 3
You can change this pins to any digital pins that are convenient for you. Thank you.
